plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate

port: 4444

exclude:
  - .idea
  - node_modules
  - Gemfile.lock
  - Gemfile


baseurl: ''
url:  https://barbaricum.kiev.ua

paginate: 10
paginate_path: /news/page-:num/

#analytics: UA-25258708-4
#sharethis: property=59985e446692a7001120ec59&product=inline-share-buttons

title: Barbaricum

author:
  name: Barbaricum
  url: https://barbaricum.kiev.ua/
  twitter: BarbaricumArch
  image:
    path:  /assets/favicon/android-icon-192x192.png
    height: 192
    width: 192

social:
  name: Barbaricum
  links:
    - https://twitter.com/BarbaricumArch
    - https://facebook.com/barbaricum
    - https://www.pinterest.com/kosatyi/
    - https://github.com/kosatyi/barbarcum.kiev.ua
  profiles:
    facebook: https://facebook.com/kosatyi
    twitter: https://twitter.com/kosatyi
    linkedin: https://www.linkedin.com/in/stepankosatyi/
    google: https://plus.google.com/+StepanKosatyi
    pinterest: https://www.pinterest.com/kosatyi/
    github: https://github.com/kosatyi


collections:
  archaeology:
    output: true
    permalink: '/archaeology/:path.html'
  laboratory:
    output: true
    permalink: '/laboratory/:path.html'

defaults:
  - scope:
      path: ''
    values:
      layout: 'default'
  - scope:
      path: ''
      type: 'posts'
    values:
      layout: 'article'
      permalink: '/news/:year/:month/:day/:title.html'
  - scope:
      path: '_archaeology'
    values:
      layout: "article"
  - scope:
      path: '_archaeology/legislation'
    values:
      layout: 'document'
  - scope:
      path: '_laboratory'
    values:
      layout: 'article'
