plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate
  - jekyll-redirect-from

port: 4444

exclude:
  - .idea
  - node_modules
  - Gemfile.lock
  - Gemfile


baseurl: ''
url:  https://barbaricum.kiev.ua

paginate: 10
paginate_path: /news/page-:num/

analytics: UA-25258708-4
#sharethis: property=59985e446692a7001120ec59&product=inline-share-buttons

title: Barbaricum
description: Навчальна науково-дослідна лабораторія археологічних досліджень

author:
  name: Barbaricum
  url: https://barbaricum.kiev.ua/
  twitter: BarbaricumArch
  image:
    path:  /assets/images/banner.png
    height: 720
    width: 480

social:
  name: Barbaricum
  links:
    - https://twitter.com/BarbaricumArch
    - https://facebook.com/barbaricum
    - https://github.com/kosatyi/barbarcum.kiev.ua


collections:
  archaeology:
    output: true
    permalink: '/archaeology/:path.html'
  laboratory:
    output: true
    permalink: '/laboratory/:path.html'
  journal:
    output: true
    permalink: '/journal/:path.html'

defaults:
  - scope:
      path: ''
    values:
      layout: 'default'
      cover:
        path:  'https://i.imgur.com/5WJwhWh.jpg'
      image:
        path:  '/assets/images/banner.png'
        height: 720
        width: 480
  - scope:
      path: ''
      type: 'posts'
    values:
      layout: 'article'
      permalink: '/news/:year/:month/:day/:title.html'
  - scope:
      path: '_archaeology'
    values:
      layout: "article"
  - scope:
      path: '_archaeology/legislation'
    values:
      layout: 'document'
  - scope:
      path: '_laboratory'
    values:
      layout: 'article'
  - scope:
      path: '_journal'
    values:
      layout: 'journal'
