plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate

port: 4444

exclude:
  - .idea
  - node_modules
  - Gemfile.lock
  - Gemfile


baseurl: ''
url:  https://kosatyi.com

paginate: 10
paginate_path: /blog/page-:num/

#analytics: UA-25258708-4
#sharethis: property=59985e446692a7001120ec59&product=inline-share-buttons

title: Barbaricum

author:
  name: Stepan Kosatyi
  url: https://kosatyi.com/
  twitter: kosatyi
  image:
    path:  /assets/images/profile.jpg
    height: 512
    width: 512

social:
  name: Stepan Kosatyi
  links:
    - https://plus.google.com/+StepanKosatyi
    - https://twitter.com/kosatyi
    - https://facebook.com/kosatyi
    - https://www.pinterest.com/kosatyi/
    - https://www.linkedin.com/in/stepankosatyi/
    - https://github.com/kosatyi
  profiles:
    facebook: https://facebook.com/kosatyi
    twitter: https://twitter.com/kosatyi
    linkedin: https://www.linkedin.com/in/stepankosatyi/
    google: https://plus.google.com/+StepanKosatyi
    pinterest: https://www.pinterest.com/kosatyi/
    github: https://github.com/kosatyi

collections_dir: _collections

collections:
  laboratory:
    output: true
    permalink: '/laboratory/:categories/:title.html'
  archaeology:
    output: true
    permalink: '/archaeology/:categories/:title.html'
  history:
    output: true
    permalink: '/history/:categories/:title.html'
  articles:
    output: true
    permalink: '/archaeology/articles/:title.html'
  fonds:
    output: true
    permalink: '/archaeology/fonds/:title.html'
  legislation:
    output: true
    permalink: '/archaeology/legislation/:title.html'
    layout: "doc"
  reports:
    output: true
    permalink: '/archaeology/reports/:title.html'
  posts:
    output: true
    permalink: '/blog/:year/:month/:day/:title.html'

defaults:
  -
    scope:
      path: ''
    values:
      layout: 'default'
  - scope:
      path: ""
      type: "archaeology"
    values:
      layout: "article"
  - scope:
      path: ""
      type: "history"
    values:
      layout: "article"
  - scope:
      path: ""
      type: "laboratory"
    values:
      layout: "article"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "article"
  - scope:
      path: ""
      type: "articles"
    values:
      layout: "article"
  - scope:
      path: ""
      type: "fonds"
    values:
      layout: "article"
  - scope:
      path: ""
      type: "reports"
    values:
      layout: "article"
  - scope:
      path: ""
      type: "legislation"
    values:
      layout: "doc"